version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/pms-processPension-service-SP:2"
        LoadBalancerInfo:
          ContainerName: "pms-processPension-service-SP"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"